version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/app
    environment:
      - APP_ENV=local
    command: ["apache2-foreground"]
